### ISSUE TITLE
undefined method 'path=' on start

### ISSUE THREAD

**Issue by domofactor** [padrino/padrino-contrib#30]
hey guys,

i'm just getting started with padrino, but seem to be running into this error on startup when trying to use master of padrino-contrib. I'm running padrino version 0.13.1 and switching to padrino-contrib 0.1.13 I noticed this error goes away. any thoughts? I'll include my stacktrace and app file below. Thanks!

#### app.rb
```
  class App < Padrino::Application
    register Padrino::Contrib::AutoLocale
    set :locales, [:en, :ja]
    set :locale_exclusive_paths, ['/js', '/css', '/img']
```

#### Stacktrace
```
  ERROR -  NoMethodError - undefined method `path=' for #<Padrino::PathRouter::Route:0x00000002dfd1d8>:
 /usr/local/rvm/gems/ruby-2.2.1@soukoukai/bundler/gems/padrino-contrib-e6820a56b413/lib/padrino-contrib/auto_locale.rb:88:in `padrino_route_added'
/usr/local/rvm/gems/ruby-2.2.1@soukoukai/bundler/gems/padrino-contrib-e6820a56b413/lib/padrino-contrib/auto_locale.rb:88:in `padrino_route_added': undefined method `path=' for #<Padrino::PathRouter::Route:0x0000000353e7d0> (NoMethodError)
	from /usr/local/rvm/gems/ruby-2.2.1@soukoukai/gems/sinatra-1.4.7/lib/sinatra/base.rb:1591:in `block in invoke_hook'
	from /usr/local/rvm/gems/ruby-2.2.1@soukoukai/gems/sinatra-1.4.7/lib/sinatra/base.rb:1591:in `each'
	from /usr/local/rvm/gems/ruby-2.2.1@soukoukai/gems/sinatra-1.4.7/lib/sinatra/base.rb:1591:in `invoke_hook'
	from /usr/local/rvm/gems/ruby-2.2.1@soukoukai/gems/padrino-core-0.13.1/lib/padrino-core/application/routing.rb:555:in `route'
	from /usr/local/rvm/gems/ruby-2.2.1@soukoukai/gems/padrino-core-0.13.1/lib/padrino-core/application/routing.rb:357:in `get'
	from /usr/local/rvm/gems/ruby-2.2.1@soukoukai/gems/padrino-core-0.13.1/lib/padrino-core/application/application_setup.rb:123:in `block in default_routes'
	from /usr/local/rvm/gems/ruby-2.2.1@soukoukai/gems/sinatra-1.4.7/lib/sinatra/base.rb:1411:in `configure'
	from /usr/local/rvm/gems/ruby-2.2.1@soukoukai/gems/padrino-core-0.13.1/lib/padrino-core/application/application_setup.rb:122:in `default_routes'
	from /usr/local/rvm/gems/ruby-2.2.1@soukoukai/gems/padrino-core-0.13.1/lib/padrino-core/application/application_setup.rb:40:in `setup_application!'
	from /usr/local/rvm/gems/ruby-2.2.1@soukoukai/gems/padrino-core-0.13.1/lib/padrino-core/mounter.rb:114:in `map_onto'
	from /usr/local/rvm/gems/ruby-2.2.1@soukoukai/gems/padrino-core-0.13.1/lib/padrino-core.rb:73:in `block in application'
	from /usr/local/rvm/gems/ruby-2.2.1@soukoukai/gems/padrino-core-0.13.1/lib/padrino-core.rb:73:in `each'
	from /usr/local/rvm/gems/ruby-2.2.1@soukoukai/gems/padrino-core-0.13.1/lib/padrino-core.rb:73:in `application'
	from config.ru:9:in `block in <main>'
	from /usr/local/rvm/gems/ruby-2.2.1@soukoukai/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /usr/local/rvm/gems/ruby-2.2.1@soukoukai/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from config.ru:in `new'
	from config.ru:in `<main>'
	from /usr/local/rvm/gems/ruby-2.2.1@soukoukai/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
	from /usr/local/rvm/gems/ruby-2.2.1@soukoukai/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
	from /usr/local/rvm/gems/ruby-2.2.1@soukoukai/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
	from /usr/local/rvm/gems/ruby-2.2.1@soukoukai/gems/padrino-core-0.13.1/lib/padrino-core/server.rb:24:in `detect_application'
	from /usr/local/rvm/gems/ruby-2.2.1@soukoukai/gems/padrino-core-0.13.1/lib/padrino-core/server.rb:12:in `run!'
	from /usr/local/rvm/gems/ruby-2.2.1@soukoukai/gems/padrino-core-0.13.1/lib/padrino-core/cli/adapter.rb:7:in `start'
	from /usr/local/rvm/gems/ruby-2.2.1@soukoukai/gems/padrino-core-0.13.1/lib/padrino-core/cli/launcher.rb:30:in `start'
	from /usr/local/rvm/gems/ruby-2.2.1@soukoukai/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/rvm/gems/ruby-2.2.1@soukoukai/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/rvm/gems/ruby-2.2.1@soukoukai/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/rvm/gems/ruby-2.2.1@soukoukai/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/rvm/gems/ruby-2.2.1@soukoukai/gems/padrino-core-0.13.1/bin/padrino:8:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.1@soukoukai/bin/padrino:23:in `load'
	from /usr/local/rvm/gems/ruby-2.2.1@soukoukai/bin/padrino:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.2.1@soukoukai/bin/ruby_executable_hooks:15:in `eval'
```

**Comment by carlqt** [comment]
I will be releasing a pull request fixing this issue but for now you can patch it up by opening up the file with the error, in your case `/usr/local/rvm/gems/ruby-2.2.1@soukoukai/bundler/gems/padrino-contrib-e6820a56b413/lib/padrino-contrib/auto_locale.rb`, go to line 88 and then change the setter from `route.path = ...` to `route.path_for_generation = ...`

**Comment by wikimatze** [comment]
Hi @carlqt thanks for helping out. @domofactor have you already tried Padrino 0.13.2?

**Comment by wikimatze** [comment]
@carlqt did you already made the pull request or do you need help?

**Comment by carlqt** [comment]
@wikimatze Oh sorry about that, I haven't created the pull request because `Padrino 0.13.2` works fine here. I'm not familiar about the rules so I just assumed that the best fix was to update.
